{% set name = "django-queryset-feeler" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-queryset-feeler-{{ version }}.tar.gz
  sha256: 1d8066b08f010c94aec0ddedaa91851a4334fe663e01c8e558c2e7dbdced0219

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=42
  run:
    - django
    - ipython
    - pygments
    - python >={{ python_min }}
    - sql-metadata
    - sqlparse

test:
  imports:
    - django_queryset_feeler
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lukas-schillinger/django-queryset-feeler
  summary: tools to help understand how django querysets are executed
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
