{% set name = "django-queryset-feeler" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-queryset-feeler-{{ version }}.tar.gz
  sha256: 2e6f92bbb7f1bb1982a8ebdbc8d44099188164308b8b7577ff1a7e9710a1f2c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=42
  run:
    - django
    - ipython
    - pygments
    - python >=3.6
    - sql-metadata
    - sqlparse

test:
  imports:
    - django_queryset_feeler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lukas-schillinger/django-queryset-feeler
  summary: tools to help understand how django querysets are executed
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
